### ISSUE TITLE
UI Reloads every 10-20 seconds after upgrade to Graylog 2.1.3

### ISSUE THREAD

**Issue by centralscrutiniser** [Graylog2/graylog-plugin-threatintel#24] opened 2017-02-05 17:22 UTC
Using 0.9 version of the Threat Intel plugin causes the UI to reload every 10-20 seconds. 

Issue #23 notes problem, but closed. 
Issue #3448 on Graylog2 Git notes issue, but user who reported it was running old Graylog2 Plugins from source TGZ. 

I've got a similar issue with .deb installed Graylog2 from Repo's with two separate servers following an install/upgrade to Graylog 2.1.3. 

If I remove the Threat Intel plugin (v0.9) and reboot, the issue goes away.

**Comment by Dr-Crow** [comment] 2017-02-05 22:02
I can confirm. Having exactly the same issue. Once Threat Intel plugin is removed Graylog goes back to normal. I have all the default versions of the other plugins.

**Comment by gruselglatz** [comment] 2017-02-13 11:47
I too can confirm this issue. We have the same problem on 2.2

**Comment by jalogisch** [comment] 2017-02-17 13:37
this is a duplicate of https://github.com/Graylog2/graylog-plugin-threatintel/issues/23 slow now

**Closed by jalogisch** 2017-02-17 13:37 UTC
